FROM scratch
ENV LAST_UPDATE=20180921
LABEL authors="Joost van der Griendt <joostvdg@gmail.com>"
LABEL version="0.1.0"
LABEL description="Docker image for CAT"
ENTRYPOINT ["catz", "serve"]
COPY cat /usr/local/bin/catz
